### ISSUE TITLE
deadlock of cache handler at interpreter shutdown

### ISSUE THREAD

**Issue by anntzer** [hgomersall/pyFFTW#69]
Consider this example `deadlock.py`:
```
import sys
import pyfftw
import scipy
sys.modules["scipy.fftpack"] = scipy.fftpack = pyfftw.interfaces.scipy_fftpack
pyfftw.interfaces.cache.enable()
import seaborn
import faulthandler
faulthandler.dump_traceback_later(2)
```
Running this multiple times with
```
$ for i in $(seq 100); do echo $i; python deadlock.py foo; done
```
yields, after a couple of iterations, a deadlock which gets reported by faulthandler:
```
Timeout (0:00:02)!
Thread 0x00007f84dbaed700 (most recent call first):
  File "/usr/lib/python3.5/site-packages/pyfftw/interfaces/cache.py", line 204 in _run
  File "/usr/lib/python3.5/threading.py", line 871 in run
  File "/usr/lib/python3.5/threading.py", line 923 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 891 in _bootstrap

Thread 0x00007f84e3f60700 (most recent call first):
  File "/usr/lib/python3.5/threading.py", line 1079 in _wait_for_tstate_lock
  File "/usr/lib/python3.5/threading.py", line 1063 in join
  File "/usr/lib/python3.5/site-packages/pyfftw/interfaces/cache.py", line 162 in __del__
```

Yes, this is a somewhat random collection of modules, but in fact it seems like the more imports I have, the more I see the deadlock at the interpreter shutdown.

This is with Python3.5 and Arch Linux standard packages.

**Comment by hgomersall** [comment]
Are you using the latest git version? Is this fixed in dffe3c78?

**Comment by anntzer** [comment]
I was running 0.9.2, but a quick test with git HEAD shows that the issue is still present.

**Comment by hgomersall** [comment]
Hmm interesting - I can reproduce this on python 3.4 (but not on 2.7). I'll look into it...

**Comment by hgomersall** [comment]
(and thanks for the report!)

**Comment by hgomersall** [comment]
This should be fixed in bc3fee491a1124951bf558929d15dfac2c7f6f43. It was joining the thread at exit which led to the deadlock . I'm not quite sure why it was locking up, but joining the thread is not necessary because the thread is a daemon thread. Removing it fixed the problem.

It would be good if you could confirm.

**Comment by anntzer** [comment]
Seems to work for me.

**Comment by hgomersall** [comment]
Great! Thanks for the report.
